// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Header() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"badges\" style=\"margin-bottom: 1.5rem; display: flex; gap: 0.5rem; flex-wrap: wrap; justify-content: center;\"><a href=\"https://go.dev/doc/devel/release\" target=\"_blank\" rel=\"noopener\"><img src=\"https://img.shields.io/badge/Go-1.23+-00ADD8?style=flat-square&logo=go&logoColor=white\" alt=\"Go Version\"></a> <a href=\"https://github.com/whalelogic/howtogo/stargazers\" target=\"_blank\" rel=\"noopener\"><img src=\"https://img.shields.io/github/stars/whalelogic/howtogo?style=flat-square&logo=github&color=2ea3b2\" alt=\"GitHub stars\"></a> <a href=\"https://github.com/whalelogic/howtogo\" target=\"_blank\" rel=\"noopener\"><img src=\"https://img.shields.io/github/license/whalelogic/howtogo?style=flat-square&color=2ea3b2\" alt=\"License\"></a> <a href=\"https://github.com/whalelogic\" target=\"_blank\" rel=\"noopener\"><img src=\"https://img.shields.io/badge/GitHub-whalelogic-90EE90?style=flat-square&logo=github&logoColor=white\" alt=\"whalelogic on GitHub\"></a></div><div class=\"home-intro\"><p><a href=\"https://go.dev\"><b>Go</b></a> is an open source programming language designed for building scalable, secure, and reliable software. Go combines the performance of C with features like  <b>garbage collection</b>, <b>concurrency</b>, and a strong <b>type system</b>.</p><p style=\"margin-top: 1em;\"><span class=\"brand-name\"><a href=\"/\">How to Go</a></span> is a modern, hands-on language reference. Master everything from syntax to advanced patterns through annotated examples. </p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
