// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/whalelogic/howtogo/views/layouts"
import "github.com/whalelogic/howtogo/views/components"

func XML() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = components.Breadcrumb("xml", "XML").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.CustomHeader("XML", "Time").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " <p>XML (Extensible Markup Language) is a markup language for encoding documents in a format that is both human-readable and machine-readable.  Go's encoding/xml package provides built-in support for encoding Go data structures to XML and decoding XML into Go structures using struct tags similar to JSON.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.KeyPoints([]string{
				"Use struct tags to control XML element names and attributes",
				"XMLName field controls the root element name",
				"Use <code>xml.Marshal()</code> to encode and <code>xml.Unmarshal()</code> to decode",
				"The <code>attr</code> tag marks a field as an XML attribute",
				"The <code>chardata</code> tag marks character data content",
				"Use <code>xml.Encoder</code> and <code>xml.Decoder</code> for streaming",
				"Support for namespaces, CDATA, comments, and processing instructions",
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " <h2>Encoding to XML</h2><p>Convert Go data structures to XML using xml.Marshal:</p><div class=\"code-block\"><pre><code class=\"language-go\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.Raw(`package main

import (
    "encoding/xml"
    "fmt"
)

type Person struct {
    XMLName xml.Name `+"`xml:\"person\"`"+`
    Name    string   `+"`xml:\"name\"`"+`
    Age     int      `+"`xml:\"age\"`"+`
    Email   string   `+"`xml:\"email\"`"+`
}

func main() {
    p := Person{
        Name:   "Alice",
        Age:   30,
        Email: "alice@example.com",
    }
    
    xmlData, err := xml.MarshalIndent(p, "", "  ")
    if err != nil {
        fmt.Println("error:", err)
        return
    }
    
    fmt. Println(xml.Header + string(xmlData))
}`).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</code></pre></div><span class=\"output-label\">Output:</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.CodeOutput(`<?xml version="1.0" encoding="UTF-8"?>
<person>
  <name>Alice</name>
  <age>30</age>
  <email>alice@example.com</email>
</person>`).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, " <h2>Decoding from XML</h2><p>Parse XML into Go structures using xml.Unmarshal:</p><div class=\"code-block\"><pre><code class=\"language-go\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.Raw(`package main

import (
    "encoding/xml"
    "fmt"
)

type Person struct {
    XMLName xml.Name `+"`xml:\"person\"`"+`
    Name    string   `+"`xml:\"name\"`"+`
    Age     int      `+"`xml:\"age\"`"+`
    Email   string   `+"`xml:\"email\"`"+`
}

func main() {
    xmlStr := `+"`"+`
    <person>
        <name>Bob</name>
        <age>25</age>
        <email>bob@example.com</email>
    </person>
    `+"`"+`
    
    var p Person
    err := xml.Unmarshal([]byte(xmlStr), &p)
    if err != nil {
        fmt.Println("error:", err)
        return
    }
    
    fmt.Printf("Name: %s, Age:  %d, Email: %s\n", p.Name, p. Age, p.Email)
}`).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</code></pre></div><span class=\"output-label\">Output:</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.CodeOutput(`Name: Bob, Age: 25, Email: bob@example.com`).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, " <h2>XML Attributes and Nested Elements</h2><p>XML supports attributes and nested structures:</p><div class=\"code-block\"><pre><code class=\"language-go\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.Raw(`package main

import (
    "encoding/xml"
    "fmt"
)

type Address struct {
    City    string `+"`xml:\"city\"`"+`
    Country string `+"`xml:\"country\"`"+`
}

type Person struct {
    XMLName xml.Name `+"`xml:\"person\"`"+`
    ID      int      `+"`xml:\"id,attr\"`"+`
    Name    string   `+"`xml:\"name\"`"+`
    Address Address  `+"`xml:\"address\"`"+`
}

func main() {
    p := Person{
        ID:   123,
        Name: "Charlie",
        Address: Address{
            City:    "New York",
            Country: "USA",
        },
    }
    
    xmlData, _ := xml.MarshalIndent(p, "", "  ")
    fmt.Println(xml. Header + string(xmlData))
}`).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</code></pre></div><span class=\"output-label\">Output:</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.CodeOutput(`<?xml version="1.0" encoding="UTF-8"?>
<person id="123">
  <name>Charlie</name>
  <address>
    <city>New York</city>
    <country>USA</country>
  </address>
</person>`).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, " <h2>Struct Tag Options</h2><table class=\"reference-table\"><thead><tr><th>Tag</th><th>Example</th><th>Description</th></tr></thead> <tbody><tr><td>Element Name</td><td><code>` + \"`xml:\\\"elementname\\\"`\" + `</code></td><td>Sets XML element name</td></tr><tr><td>Attribute</td><td><code>` + \"`xml:\\\"name,attr\\\"`\" + `</code></td><td>Field becomes an attribute</td></tr><tr><td>Character Data</td><td><code>` + \"`xml:\\\",chardata\\\"`\" + `</code></td><td>Field contains element content</td></tr><tr><td>CDATA</td><td><code>` + \"`xml:\\\",cdata\\\"`\" + `</code></td><td>Wrap content in CDATA section</td></tr><tr><td>Inner XML</td><td><code>` + \"`xml:\\\",innerxml\\\"`\" + `</code></td><td>Raw XML content</td></tr><tr><td>Comment</td><td><code>` + \"`xml:\\\",comment\\\"`\" + `</code></td><td>XML comment</td></tr><tr><td>Any Element</td><td><code>` + \"`xml:\\\",any\\\"`\" + `</code></td><td>Match any element</td></tr><tr><td>Omit Empty</td><td><code>` + \"`xml:\\\"name,omitempty\\\"`\" + `</code></td><td>Omit if zero value</td></tr><tr><td>Ignore Field</td><td><code>` + \"`xml:\\\"-\\\"`\" + `</code></td><td>Skip field entirely</td></tr></tbody></table><h2>XML Encoding Functions</h2><table class=\"reference-table\"><thead><tr><th>Function</th><th>Signature</th><th>Use Case</th></tr></thead> <tbody><tr><td>Marshal</td><td><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs("Marshal(v interface{}) ([]byte, error)")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/xml.templ`, Line: 224, Col: 57}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</code></td><td>Encode to compact XML</td></tr><tr><td>MarshalIndent</td><td><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs("MarshalIndent(v interface{}, prefix, indent string) ([]byte, error)")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/xml.templ`, Line: 229, Col: 86}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</code></td><td>Encode to formatted XML</td></tr><tr><td>Unmarshal</td><td><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs("Unmarshal(data []byte, v interface{}) error")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/xml.templ`, Line: 234, Col: 62}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</code></td><td>Decode XML into struct</td></tr><tr><td>NewEncoder</td><td><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs("NewEncoder(w io.Writer) *Encoder")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/xml.templ`, Line: 239, Col: 51}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</code></td><td>Create streaming encoder</td></tr><tr><td>NewDecoder</td><td><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs("NewDecoder(r io.Reader) *Decoder")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/xml.templ`, Line: 244, Col: 51}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</code></td><td>Create streaming decoder</td></tr></tbody></table><h2>Type Mappings</h2><table class=\"reference-table\"><thead><tr><th>Go Type</th><th>XML Representation</th><th>Notes</th></tr></thead> <tbody><tr><td>bool</td><td>true/false</td><td>Boolean values</td></tr><tr><td>int, int8, int16, int32, int64</td><td>Decimal number</td><td>Integer values</td></tr><tr><td>uint, uint8, uint16, uint32, uint64</td><td>Decimal number</td><td>Unsigned integer values</td></tr><tr><td>float32, float64</td><td>Decimal number</td><td>Floating-point values</td></tr><tr><td>string</td><td>Character data</td><td>Text content</td></tr><tr><td>[]byte</td><td>Base64-encoded</td><td>Binary data</td></tr><tr><td>[]T</td><td>Multiple elements</td><td>Repeated elements</td></tr><tr><td>struct</td><td>Nested elements</td><td>Complex structures</td></tr><tr><td>*T</td><td>Element or omitted</td><td>Optional elements</td></tr><tr><td>xml.Name</td><td>Element name</td><td>Controls root element</td></tr></tbody></table><h2>Common XML Patterns</h2><table class=\"reference-table\"><thead><tr><th>Pattern</th><th>Code</th><th>Use Case</th></tr></thead> <tbody><tr><td>With XML Header</td><td><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs("xml. Header + string(xmlData)")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/xml.templ`, Line: 323, Col: 48}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</code></td><td>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var9 string
			templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs("Include <? xml version=1.0?>")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/xml.templ`, Line: 324, Col: 41}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</td></tr><tr><td>Stream Encoding</td><td><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 string
			templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs("xml.NewEncoder(w).Encode(v)")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/xml.templ`, Line: 328, Col: 46}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "</code></td><td>Write directly to io.Writer</td></tr><tr><td>Stream Decoding</td><td><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs("xml.NewDecoder(r).Decode(&v)")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/xml.templ`, Line: 333, Col: 47}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "</code></td><td>Read from io.Reader</td></tr><tr><td>Token-Based Parsing</td><td><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var12 string
			templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs("for { token, _ := decoder.Token(); ...  }")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/xml.templ`, Line: 338, Col: 60}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "</code></td><td>Low-level XML parsing</td></tr><tr><td>Custom Marshal</td><td><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var13 string
			templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs("func (t T) MarshalXML(e *Encoder, start StartElement) error")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/xml.templ`, Line: 343, Col: 78}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "</code></td><td>Custom encoding logic</td></tr><tr><td>Custom Unmarshal</td><td><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var14 string
			templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.JoinStringErrs("func (t *T) UnmarshalXML(d *Decoder, start StartElement) error")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/xml.templ`, Line: 348, Col: 81}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var14))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "</code></td><td>Custom decoding logic</td></tr><tr><td>Namespace Handling</td><td><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var15 string
			templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.JoinStringErrs("XMLName xml. Name `xml:\\\"http://example.com/ns elementname\\\"`")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/xml.templ`, Line: 353, Col: 84}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var15))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "</code></td><td>Work with XML namespaces</td></tr></tbody></table><h2>XML Features</h2><table class=\"reference-table\"><thead><tr><th>Feature</th><th>Example</th><th>Description</th></tr></thead> <tbody><tr><td>Attributes</td><td><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var16 string
			templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.JoinStringErrs("ID int `xml:\\\"id,attr\\\"`")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/xml.templ`, Line: 370, Col: 47}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var16))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "</code></td><td>Add attributes to elements</td></tr><tr><td>Namespaces</td><td><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var17 string
			templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.JoinStringErrs("xml.Name{Space:  \\\"http://...\\\", Local: \\\"name\\\"}")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/xml.templ`, Line: 375, Col: 76}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var17))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "</code></td><td>XML namespace support</td></tr><tr><td>CDATA Sections</td><td><code>` + \"`xml:\\\",cdata\\\"`\" + `</code></td><td>Preserve special characters</td></tr><tr><td>Comments</td><td><code>` + \"`xml:\\\",comment\\\"`\" + `</code></td><td>XML comments</td></tr><tr><td>Processing Instructions</td><td><code>xml.ProcInst</code></td><td>Processing directives</td></tr><tr><td>Character Entities</td><td>Automatic escaping</td><td>&lt;, &gt;, &amp;, etc.</td></tr><tr><td>Directives</td><td><code>xml.Directive</code></td><td>DOCTYPE and other directives</td></tr></tbody></table><div class=\"nav-buttons\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Button("Previous: JSON", "/json").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Button("Next: Time", "/time").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base("XML | How to Go").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
