name: Deploying HowToGO to AlmaLinux

on:
  push:
    branches:
      - main  # Set default branch 

jobs:
  deploy:
    runs-on: ubuntu-latest # Github's computer, not mine
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Let me know if the script fails. Stops on error.
            set -e 
            # Navigate to the app folder
            cd /var/www/howtogo
            
            # Pull the latest code
            # Or use /usr/local/go/bin/go build -o howtogo
            # git fetch with git reset --head origin/main may be better for CI/CD
            git pull origin main
            
            # Rebuild the app
            # Can use /usr/local/go/bin/go build -o howtogo if not in PATH
            go build -o howtogo

            # Security: Ensure the new binary has the correct SELinux label
            chcon -t bin_t howtogo
            
            # Restart the service to pick up changes
            systemctl restart howtogo
